server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wa1yan/spring-cloud-config-data
          default-label: main
          search-paths: '{application}'
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: true
          timeout: 10
          username: username
          password: password
          refresh-rate: 30

    bus:
      enabled: true
      env:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: http://localhost:29092
#  kafka:
#    bootstrap-servers:
#      - http://localhost:29092

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        cloud: DEBUG